[package]
name = "connect4"
version = "0.2.0"
edition = "2021"
default-run = "connect4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.0"
crossterm = "0.26.1"

[[bin]]
name = "events"
path = "events.rs"
